### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by FetasSir** [tsgsOFFICIAL/CS2-AutoAccept.exe#5]
For me it doesn't work i tried with a wireless mouse then i connected it with a cable, still not working.I tried matching resolution of my screen to game resolution, still not working. The program recognizes i have cs2 started but doesn't auto accept.

**Comment by FetasSir** [comment]
I tried again now it says the handle is invalid in a pop up.

![Screenshot_1](https://github.com/user-attachments/assets/b0c8415d-20b0-4e20-85b2-f3b8ef2c2851)

**Comment by tsgsOFFICIAL** [comment]
Thank you for reporting the issue.

Firstly could you confirm that you have installed it in the correct directory, as instructed in the [README](../#where-can-i-download-this).

If true, can you then please provide more details about your setup, such as your operating system and any error messages you see, if any others.
Remember to check within Windows Event Viewer, to see any errors.

Please also tell me which part of the program is not working, and what you were doing when you encountered the problem.

This information will help me diagnose and fix the problem.

Ps. I can assure you that your mouse has nothing to do with the program, it will even work without one.

**Comment by FetasSir** [comment]
I installed everything like instructions said.

OS: Windows 11 version 23H2

I had one error message "The handle is invalid", and it only showed up once and never again, other than that I had an error when pressing the top left cs icon and text "CS2 AutoAccept by tsgsOFFICIAL" next to it. 
![Screenshot_1](https://github.com/user-attachments/assets/9c2e1089-b221-46ad-8912-5ce0c4434f4f)
↑ clicking this crashes the app

The only error i see in event viewer is about the app crash
[cs2 error.zip](https://github.com/user-attachments/files/17663493/cs2.error.zip)

I didn't do anything special when trying the app, I started premier search while the app was open with all 3 checkboxes ticked, than accept button appears and nothing happens the countdown just expires.

Thank you for a fast respond though.

**Comment by tsgsOFFICIAL** [comment]
> I installed everything like instructions said.
> 
> OS: Windows 11 version 23H2
> 
> I had one error message "The handle is invalid", and it only showed up once and never again, other than that I had an error when pressing the top left cs icon and text "CS2 AutoAccept by tsgsOFFICIAL" next to it. ![Screenshot_1](https://private-user-images.githubusercontent.com/168601672/384012428-9c2e1089-b221-46ad-8912-5ce0c4434f4f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTQ1MjEsIm5iZiI6MTczMDk5NDIyMSwicGF0aCI6Ii8xNjg2MDE2NzIvMzg0MDEyNDI4LTljMmUxMDg5LWIyMjEtNDZhZC04OTEyLTVjZTBjNDQzNGY0Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNTQzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjdhMDU1ZDZkZjZmZDFmOWNmMjIyY2FlODI4NGRlOGU1YjEwYjE5ODQ4YmExYmE3NDRmYjFlZmI1OTRkOTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oOG-btbDjV4wH3YPTDKkC3VGMhujJPRKx_cM63mxC3M) ↑ clicking this crashes the app
> 
> The only error i see in event viewer is about the app crash [cs2 error.zip](https://github.com/user-attachments/files/17663493/cs2.error.zip)
> 
> I didn't do anything special when trying the app, I started premier search while the app was open with all 3 checkboxes ticked, than accept button appears and nothing happens the countdown just expires.
> 
> Thank you for a fast respond though.

Thank you for providing me with the details, I'm assuming you are on the latest version (V. 5.1.5.3)?
I see the error you provided seems to stem from the drag functionality of the window, and should not have anything to do with the actual software. However this obviously needs to be patched aswell, and will be in the next 12 hours (V. 5.1.5.4).

Can you tell me about the monitor you're using, specifically the size, and any scaling that you might have enabled in windows setings and or in CS2.

For example:
Screen Size (where CS2 runs, in case you have more): 2560x1440
Windows Settings Scale: 100%
CS2 Resolution: Windowed, 2560x1440, Widescreen 16:9
CS2 AutoAccept Display Size (What size appears when using CS2 AutoAccept): 2560x1440 (16:9)
↑
![CS2-AutoAccept - 266](https://github.com/user-attachments/assets/58d9d90a-4510-4c87-b498-ca0b7eb1d8da)

Hopefully with this information I'll be able to re-create your error & fix it.

**Comment by tsgsOFFICIAL** [comment]
The crashing behaviour is now fixed, as of version 5.1.5.4.
I'm still investigating the **Handle Error**.

**Comment by FetasSir** [comment]
Yes, I am on the latest version.
I have some old monitor: Samsung SyncMaster 2243
Screen Size: 1920x1080 (60hz)
Windows Settings Scale: 100%
CS2 Resolution: Fullscreen, 1280x960, Normal 4:3 (stretched), 60hz
CS2 AutoAccept Display Size : 1920x1080 (16:9), but for a split second I can see the 1280x960 (4:3) when alt-tabbing.

**Comment by tsgsOFFICIAL** [comment]
Do you only have one monitor?

**Comment by FetasSir** [comment]
yes

**Comment by tsgsOFFICIAL** [comment]
![cs2 - 269](https://github.com/user-attachments/assets/b46845ce-c699-45ae-84dc-e4892935da97)
Is this your settings?

**Comment by FetasSir** [comment]
Yes

**Comment by FetasSir** [comment]
I just changed to Widescreen 16:9 1920x1080 and it worked, so it's probably about my game resolution.

**Comment by tsgsOFFICIAL** [comment]
I'm working on a solution for your resolution right now, it would appear as the "confidence" of the OCR reading is below the threshold, and therefore won't activate.

I'm trying my best to up it, digitally.

I'll keep you posted.

**Comment by tsgsOFFICIAL** [comment]
Version 5.1.5.5 is out now, and should hopefully solve your issue.

<details><summary>Solution</summary>
<p>
It features a more complex AutoAccept solution, where it now searches for "ACCEPT", if that's found it tries to measure its confidence. Previously this had to be above 75%, but I've lowered it to 50%.
Also instead of only using confidence levels to determine the button, it now uses the individual pixels on the screen, to measure the average pixel color, if thats the same color as the accept button, and the word accept is there, the button is probably there! 😄

This should hopefully solve your issue when using a lower resolution.
</p>
</details> 

Should there be any more issues, feel free to reach out, either by creating a [new issue](https://github.com/tsgsOFFICIAL/CS2-AutoAccept/issues/new), or on [Discord](https://discord.gg/Cddu5aJ).
- _tsgsOFFICIAL_

**Comment by FetasSir** [comment]
Thank you for a quick solution it's working like a charm, really appreciate it.
